### ISSUE TITLE
xmldom error

### ISSUE THREAD

**Issue by bansal-rahul** [vault-development/react-native-svg-uri#122]
Simpson image given in example works fine when loaded from network. But gives following error when I try to load it by passing svg string to svgXmlData prop or as a static file
"**xmldom error - invalid doc source @#[line:0,col:undefined]**"

**Comment by prscX** [comment]
@bansal-rahul: Looks like the issue was solution on your end. Can you please share the solution since I am also facing the similar issue.

Thanks
Pranav

**Comment by bansal-rahul** [comment]
@prscX 
Check the validity of your svg source string. It shouldn't contain any unnecessary tags. If it still doesn't help let me know

**Comment by prscX** [comment]
Sure, Thanks @bansal-rahul for the quick response.

Thanks
Pranav
