### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNSVGDefs" was not found in the UImanager.

### ISSUE THREAD

**Issue by PurnimaNaik** [vault-development/react-native-svg-uri#159]
Getting `Invariant Violation: requireNativeComponent: "RNSVGDefs" was not found in the UImanager.` with a red screen for my React-native app. Have added `react-native-svg`, modified the pod files. IAny leads??

**Comment by PurnimaNaik** [comment]
`react-native link react-native-svg` does not work.

## Do the following manual linking and it will work fine:-

1. Open your project in XCode and drag the RNSVG.xcodeproj file (located in .../node_modules/react-native-svg/ios) into the Libraries directory shown in XCode.

2. Expand the RNSVG.xcodeproj file you just added to XCode until you see: libRNSVG.a (located in RNSVG.xcodeproj > Products )

3. Drag libRNSVG.a into the Link Binary With Libraries section (located in Build Phases which may be found at the top of the XCode window)

**Comment by scZhengChao** [comment]
android ？
