### ISSUE TITLE
I can't resize the SVGs

### ISSUE THREAD

**Issue by msqar** [vault-development/react-native-svg-uri#185]
I can't seem to find a way to resize the SVGs, no matter what I do, it would "resize" the container but not the image itself... it looks like an `overflow: hidden` from CSS where it hides part of my SVG, but it doesn't contain the image when I do it.

Any way to solve this?

**Comment by santialur** [comment]
Same thing going on with me

**Comment by msqar** [comment]
@santialur hey whats up, looks like it's due to an SVG i made that doesn't allow me to resize but, because i made other SVGs that were totally resizable... there has to be some logic put into this that makes your SVG unresizable.. don't know what it is.

**Comment by santialur** [comment]
does it have a mask? or do you Identify a tag inside the SVG that is not on the resizable ones?

**Comment by msqar** [comment]
@santialur yes, i have to check on that. Whenever i can i will check it out and see what's causing this. It might be certain tag. I did the SVGs on Pixelmator Pro. It's weird because the unresizable one is suuuper basic, almost one-liner.

**Comment by msqar** [comment]
Okay so it was indeed my SVG and the way i created it. I can close this one.

**Comment by over-engineer** [comment]
@msqar I'm dealing with the same problem. Would you mind sharing a few details on the issue with your SVGs?
