### ISSUE TITLE
Does the Bug still Exist? For Release APK

### ISSUE THREAD

**Issue by pavantekal** [vault-development/react-native-svg-uri#188]
Does the bug still exits for release resource as mention in the description?, If yes, what is the workaround?

**Comment by ispirLee25** [comment]
I wonder the same thing

**Comment by ArfaouiHamouda** [comment]
I did fix this issue try to check my answer on this [issue](https://github.com/vault-development/react-native-svg-uri/issues/12) , let me know if any detailed explanation needed.
