### ISSUE TITLE
I am load local svg file but its not proper position.

### ISSUE THREAD

**Issue by bishwajeet-billme** [vault-development/react-native-svg-uri#197]
![Screenshot_20191022-130043](https://user-images.githubusercontent.com/51324140/67265798-43d44000-f4cc-11e9-95d9-b55c3e92fbdb.png)

Here is my code to react-native.

import * as React from 'react';
import { View, StyleSheet, Text } from "react-native";
// import Svg, { SvgUri } from "react-native-svg";
import SvgUri from 'react-native-svg-uri';
import NoBillSvg from '../../Images/svgfile/Telescope.svg';
import NoInternetSvg from "../../I"

export const NoBillFound=()=>{ 
    return(
      <View style={styles.view}>
          <SvgUri
              width="100"
              height="100"
              viewBox="0 0 1024 1024"
              svgXmlData={NoBillSvg}
          />
        <Text style={styles.text}>No Bills Found.</Text>
    </View>
    )
}

**Comment by grp06** [comment]
@bishwajeet-billme I have this same issue. Did you fix it?

**Comment by bishwajeet-billme** [comment]
@grp06 yes

import { SvgXml } from 'react-native-svg';
import NoBillSvg from '../../Images/svgfile/Telescope.svg';

SvgXml xml={NoBillSvg} width="60" height="60"   

Actually, in svg-uri having issue to render svg file so,
Instead of using svgUri,  I am using svgXml to render svg file.
