### ISSUE TITLE
Getting errors while trying to run

### ISSUE THREAD

**Issue by HeroSizy** [vault-development/react-native-svg-uri#77]
<img width="320" alt="jietu20170904-231624" src="https://user-images.githubusercontent.com/15927967/30032213-18cb10c4-91c7-11e7-8c91-305636ef9dda.png">

error copied:
`import SvgUri from 'react-native-svg-uri';`

code:
```javascript
import SvgUri from 'react-native-svg-uri';

//in Component
renderListItems () {

        const list = [
                {
                    uri: "../image/constant/homer-simpson.svg"
                },
            ]
        ;

        return list.map((l, i) =>
            <ListItem
                key={i}
                title={
                    <SvgUri height="150" width="200" source={require(l.uri)}/>
                }
            />
        );
    }
```

**Comment by matc4** [comment]
Hello @HeroSizy 

If you do:

<SvgUri height="150" width="200" source={require("../image/constant/homer-simpson.svg")}/>

Works?

**Comment by arturkasprzyk** [comment]
Hey, got exactly the same problem today on Android emulator ;)

**Comment by mhotakai** [comment]
The release is not compatible with React 16 because PropTypes has been removed from the react package. That seems to be fixed in the master branch but I ran into other problems...

**Comment by lxlneo** [comment]
fix the PropTypes ,but another problems
