### ISSUE TITLE
onLoad support

### ISSUE THREAD

**Issue by gre** [vault-development/react-native-svg-uri#79]
Have you considered adding a hook to the load event, like RN Image component have a `onLoad` prop?

one usecase is to wait the SVG is loaded before snapshotting it with react-native-view-shot (which I think is the cause of the bug raised by one of the lib user: https://github.com/gre/react-native-view-shot/issues/90 ), we can't automatically know without having a onLoad callback in this lib.

**Comment by koswarabilly** [comment]
i agree too

**Comment by pie6k** [comment]
any update about this?

**Comment by borstessi** [comment]
Like to see this!

**Comment by lorran-xo** [comment]
Nothing yet?
