### ISSUE TITLE
Comments in SVG files

### ISSUE THREAD

**Issue by danielreuterwall** [vault-development/react-native-svg-uri#97]
Hi,

In some of my SVG files I have comments added. If I add them with react-native-svg-uri I the a "Raw text..." error. I have a fix for it in my fork that works for me, 1eb99cb0ad08e9f18f6a4de96303719310d49454.
what do you think @matc4? Should I create a pull request for it?

Cheers,
Daniel

**Comment by danielreuterwall** [comment]
@matc4 Any thoughts on this?

**Comment by matc4** [comment]
@danielreuterwall Hello Daniel, i think is a good idea

**Comment by skozin** [comment]
This seems like a duplicate of #112. There is a PR that fixes this issue: #113.

**Comment by danielreuterwall** [comment]
Yep, looks like the issue. Was a bit late with my PR, great that it's being solved anyhow.
